#pragma once

#define MAX_PASSWORD_LENGTH (256)
#define MAX_PORT_NUMBER (65535)

#define MAX_EVENTS (1024)
#define MAX_MESSAGE_LENGTH (512)
#define MAX_NICKNAME_LENGTH (9)
#define MAX_CHANNEL_NAME_LENGTH (200)