name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: make server and test client
      run: make

  test-server:
    needs: build-test
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up server environment
        run: |
              make

      - name: Run server tests
        run: |
            ./ircserv 6667 1234
        timeout-minutes: 3 # 3분 타임아웃 설정

    
  test-client:
    needs: [build-test, test-server]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up client environment
        run: |
            make
          # 클라이언트를 실행하기 위한 설정
          # 예: 클라이언트를 빌드하고 실행하는 스크립트 실행

      - name: Run client tests
        run: |
            ./testClient
          # 클라이언트 테스트 실행
